name: jon tow
rouge: true
baseurl: /home

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
relative_permalinks: false

collections:
 projects: 
    output: true
    permalink: /projects/:path/